//System API
const SERVER_PING = 1011;
const SERVER_TIME = 1012;
//Today's Market status API
const TODAY_QUERY = 2000;
const TODAY_SUBSCRIBE = 2200;
//Deal API LIST
const DEAL_QUERY = 3000;
const DEAL_SUBSCRIBE = 3100;
const DEAL_UNSUBSCRIBE = 3200;
//Today's Market status API
const MARKET_QUERY = 4000;
const MARKET_SUBSCRIBE = 4100;
///Klines API
const KLINE_QUERY = 5000;
const KLINE_SUBSCRIBE = 5100;
const KLINE_UNSUBSCRIBE = 5200;
//Depth API
const DEPTH_QUERY = 6000;
const DEPTH_SUBSCRIBE = 6100;
const DEPTH_UNSUBSCRIBE = 6200;
//Auth API
const ID_VERIFICATION_WEB = 7000;
//Asset API
const ASSET_QUERY = 8000;
const ASSET_HISTORY = 8100;
const ASSET_SUBSCRIBE = 8200;
const ASSET_UNSUBSCRIBE = 8300;
//Order API
const ORDER_QUERY = 9000;
const ORDER_HISTORY = 9100;
const ORDER_SUBSCRIBE = 9200;
const ORDER_UNSUBSCRIBE = 9300;

export {
    SERVER_PING,
    SERVER_TIME,
    TODAY_QUERY,
    TODAY_SUBSCRIBE,
    DEAL_QUERY,
    DEAL_SUBSCRIBE,
    DEAL_UNSUBSCRIBE,
    MARKET_QUERY,
    MARKET_SUBSCRIBE,
    KLINE_QUERY,
    KLINE_SUBSCRIBE,
    KLINE_UNSUBSCRIBE,
    DEPTH_QUERY,
    DEPTH_SUBSCRIBE,
    DEPTH_UNSUBSCRIBE,
    ID_VERIFICATION_WEB,
    ASSET_QUERY,
    ASSET_HISTORY,
    ASSET_SUBSCRIBE,
    ASSET_UNSUBSCRIBE,
    ORDER_QUERY,
    ORDER_HISTORY,
    ORDER_SUBSCRIBE,
    ORDER_UNSUBSCRIBE
}
